definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  people.User:
    properties:
      age:
        type: integer
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      password:
        type: string
      sex:
        type: string
      updatedAt:
        type: string
      username:
        type: string
      wxOpenId:
        type: string
      wxUnionId:
        type: string
    type: object
host: 123.207.73.185:8080
info:
  contact: {}
  description: 接口文档
  title: AB迎新系统接口文档
  version: "1.0"
paths:
  /login:
    get:
      consumes:
      - application/json
      description: 用户登录请求
      parameters:
      - description: 用户id
        in: query
        name: username
        required: true
        type: string
      - description: 用户密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/people.User'
        "400":
          description: '{"code":0,"msg": "查无此人"}'
          schema:
            type: string}json
      summary: 用户登录请求
      tags:
      - 用户服务
  /login/register:
    get:
      consumes:
      - application/json
      description: 用户注册请求
      parameters:
      - description: 用户id
        in: query
        name: username
        required: true
        type: string
      - description: 用户密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"msg": "注册成功"}'
          schema:
            type: string
        "400":
          description: '{"code":0,"msg": "注册失败"}'
          schema:
            type: string
      summary: 用户注册请求
      tags:
      - 用户服务
swagger: "2.0"
